version: '3'

services:
  db:
    image: postgres:latest
    container_name: gs-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - backend/config/settings/.env
    networks:
      - main

  backend:
    image: subtlety/gs-backend:test
    container_name: gs-backend
    build:
      context: ./backend
    env_file: backend/config/settings/.env
    ports:
      - "8000:8000"
    volumes:
      - static:/collectedstatic
    networks:
      - main
    depends_on:
      - db
    command: >
      sh -c "sleep 5;
      python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      gunicorn config.wsgi --bind 0.0.0.0:8000"

  frontend:
    image: subtlety/gs-frontend:test
    container_name: gs-frontend
    build:
      context: ./frontend
    volumes:
      - frontend_build:/games_sales_frontend/build
    networks:
      - main

  nginx:
    container_name: gs-nginx
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/var/www/frontend
      - static:/collectedstatic
    networks:
      - main
    depends_on:
      - backend
      - frontend


volumes:
  frontend_build:
  postgres_data:
  static:

networks:
  main:
