# Generated by Django 4.1 on 2022-09-05 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.rating'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='other_sales',
            field=models.FloatField(blank=True, help_text='Sales in the rest of the world, i.e. Africa, Asia excluding Japan, Australia(in millions of units)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('name', 'platform')},
        ),
    ]
