# Generated by Django 4.1 on 2022-09-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_game_options_alter_game_name_alter_game_rating_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
