# Generated by Django 4.1 on 2022-09-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_game_unique_together_alter_game_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='EU_sales',
            new_name='eu_sales',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='JP_sales',
            new_name='jp_sales',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='NA_sales',
            new_name='na_sales',
        ),
    ]
