# Generated by Django 4.1 on 2022-10-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='remarks',
        ),
    ]
