# Generated by Django 4.1 on 2022-10-04 09:44

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_body',
            field=models.FileField(blank=True, upload_to=reports.models.report_upload_to),
        ),
    ]
