# Generated by Django 4.1 on 2022-11-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='report',
            name='name_user_unique',
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('slug', 'user'), name='slug_user_unique'),
        ),
    ]
